"""Trading Engine package."""

from __future__ import annotations

from app.trading.bot_lifecycle import (
    BotRuntime,
    BotRuntimeManager,
    BotStartRejected,
    BotStateError,
)
from app.trading.deal import (
    Deal,
    DealBlocked,
    DealConfigUnsupported,
    DealError,
    DealLevel,
    DealLevelStatus,
    DealOrderRejected,
    DealPositionContradiction,
    DealReconciliationRequired,
    DealStatus,
    DealTickSizeInvalid,
    InMemoryDealStore,
    align_grid_price,
    align_tp_price,
    deal_grid_intent_id,
    deal_tp_intent_id,
    round_down_to_tick,
    round_up_to_tick,
    validate_live_deal_config,
)
from app.trading.deal_manager import DealManager
from app.trading.domain import (
    ALLOWED_TRANSITIONS,
    ExecutionIntent,
    Fill,
    InternalOrder,
    OrderState,
    OrderUpdate,
    PositionUpdate,
    TradeFill,
    can_transition,
)
from app.trading.engine import TradingEngine, compose_strategy_engine
from app.trading.live_execution import LiveExecutionBlocked, LiveExecutionService
from app.trading.market_context import (
    LookbackNotConfigured,
    MarketContextUnavailable,
    TimeframeNotConfigured,
    build_market_context,
    build_market_snapshot_context,
    market_snapshot_to_context,
)
from app.trading.order_manager import OrderManager, OrderStateError
from app.trading.plan_intent import plan_to_intents
from app.trading.position_manager import (
    InvalidPositionQuantity,
    LivePositionState,
    Position,
    PositionManager,
    PositionUnavailable,
)
from app.trading.recovery import LiveRecoveryCoordinator, RecoveryResult, RecoveryStatus
from app.trading.repository import (
    InMemoryFillRepository,
    InMemoryIntentRepository,
    InMemoryOrderRepository,
    InMemoryPositionRepository,
)
from app.trading.risk_manager import RiskLimits, RiskManager, RiskRejected
from app.trading.sizing import (
    CurrencyUnavailable,
    CustomDepositExceeded,
    LotSizeUnavailable,
    PositionSizing,
    SignalSizingUnsupported,
    SizingBelowLot,
    SizingError,
    SizingNotConfigured,
    deposit_to_base_nominal,
    round_grid_to_lot,
)
from app.trading.state import InMemoryLiveStateStore, LiveStateSnapshot, LiveStateStore

__all__ = [
    "ALLOWED_TRANSITIONS",
    "BotRuntime",
    "BotRuntimeManager",
    "BotStateError",
    "BotStartRejected",
    "CurrencyUnavailable",
    "CustomDepositExceeded",
    "Deal",
    "DealBlocked",
    "DealConfigUnsupported",
    "DealError",
    "DealLevel",
    "DealLevelStatus",
    "DealManager",
    "DealOrderRejected",
    "DealPositionContradiction",
    "DealReconciliationRequired",
    "DealStatus",
    "DealTickSizeInvalid",
    "ExecutionIntent",
    "Fill",
    "InMemoryFillRepository",
    "InMemoryIntentRepository",
    "InMemoryLiveStateStore",
    "InMemoryOrderRepository",
    "InMemoryPositionRepository",
    "InMemoryDealStore",
    "InternalOrder",
    "InvalidPositionQuantity",
    "LiveExecutionBlocked",
    "LiveExecutionService",
    "LivePositionState",
    "LiveRecoveryCoordinator",
    "LiveStateSnapshot",
    "LiveStateStore",
    "LookbackNotConfigured",
    "LotSizeUnavailable",
    "MarketContextUnavailable",
    "OrderManager",
    "OrderState",
    "OrderStateError",
    "OrderUpdate",
    "Position",
    "PositionManager",
    "PositionSizing",
    "PositionUnavailable",
    "PositionUpdate",
    "RecoveryResult",
    "RecoveryStatus",
    "RiskManager",
    "RiskRejected",
    "RiskLimits",
    "SignalSizingUnsupported",
    "SizingBelowLot",
    "SizingError",
    "SizingNotConfigured",
    "TimeframeNotConfigured",
    "TradeFill",
    "TradingEngine",
    "align_grid_price",
    "align_tp_price",
    "build_market_context",
    "build_market_snapshot_context",
    "can_transition",
    "compose_strategy_engine",
    "deal_grid_intent_id",
    "deal_tp_intent_id",
    "deposit_to_base_nominal",
    "market_snapshot_to_context",
    "plan_to_intents",
    "round_down_to_tick",
    "round_grid_to_lot",
    "round_up_to_tick",
    "validate_live_deal_config",
]
